//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwinnyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string ISBN { get; set; }
        public string Title { get; set; }
        public string PublicationYear { get; set; }
        public int authorID { get; set; }
        public string authorFirstName { get; set; }
        public string authorLastName { get; set; }
        public Nullable<int> authorTaxFileNumber { get; set; }
    }
}
